services:
  memos:
    image: memos
    container_name: memos
    build:
      context: scripts/.
    volumes:
      - /home/kazuki/.memos/:/var/opt/memos
    ports:
      - 5230:5230
    restart: always
